### ISSUE TITLE
Rivedere icona espansione menu in responsive

### ISSUE THREAD

**Issue by nekorina** [italia/redturtle.agidtheme#27]
Il menu responsive non segue perfettamente le indicazioni Agid (che vorrebbe farlo apparire in offcanvas). Inoltre:
- toglierei l'uso del png (dal momento che nel codice ci sono già gli span per il font)
- la scritta menu andrebbe nel testo, non nell'immagine. In alternativa è sufficiente mettere in italiano l'indicazione "toggle menu" già presente
- per chiudere il menu deve apparire la X al posto del burger

**Comment by pnicolli** [comment]
Esempio: https://italia.github.io/design-web-toolkit/components/detail/comuni.html

**Comment by pnicolli** [comment]
Sistemato in #37
